CREATE TABLE EMPLOYEE (
    SABUN NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30),
    REGDATE DATE,
    PAY NUMBER(10)
);
INSERT INTO EMPLOYEE VALUES (1001, 'TEST1', SYSDATE - 2, 1000);
INSERT INTO EMPLOYEE VALUES (1002, 'TEST2', SYSDATE - 1, 2000);
COMMIT;

SELECT SABUN, NAME, REGDATE, PAY FROM EMPLOYEE;

