CREATE TABLE GUESTBOOK  (
    IDX NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    SUBJECT VARCHAR2(150) NOT NULL,
    CONTENT VARCHAR2(4000),
    EMAIL VARCHAR2(100),
    PWD VARCHAR2(30),
    REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE GUESTBOOK_SEQ NOCACHE;

INSERT INTO GUESTBOOK
          (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍길동', '제목1' ,'내용1', 'hong1@test.com',
            'pw1111', SYSDATE - 3);
            
INSERT INTO GUESTBOOK
          (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍길동2', '제목2' ,'내용2', 'hong2@test.com',
            'pw1111', SYSDATE - 2);

INSERT INTO GUESTBOOK
           (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍길동3', '제목3' ,'내용3', 'hong3@test.com',
            'pw1111', SYSDATE - 1);


COMMIT;


SELECT * FROM GUESTBOOK ORDER BY IDX DESC;