CREATE TABLE MEMBERS (
    IDX NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    AGE NUMBER(3),
    ADDR VARCHAR2(300),
    REGDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE MEMBERS_SEQ NOCACHE; 

INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동', 25, '서울', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동2', 30, '대전', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '김유신', 33, '대구', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '이순신', 50, '부산', SYSDATE);
COMMIT;

SELECT * FROM MEMBERS ORDER BY NAME;
